language: cpp
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: 
      - lcov
      - doxygen

install:
# (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

before_install:
  - sudo apt-get install --yes software-properties-common
  - sudo add-apt-repository --yes ppa:fenics-packages/fenics
  - sudo apt-get update --yes
  - sudo apt-get install --yes --no-install-recommends fenics

# install:

script:
    mkdir -p build && cd build
    cmake ..
    make
    ctest
    make doc
    # https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
 
# after_success:
